/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SYMBNvdHTQy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "./ui/button"
import { CardContent, Card } from "./ui/card"
import { Label } from "./ui/label"
import { Input } from "./ui/input"
import { Textarea } from "./ui/textarea"

export function HomeScreen() {
  return (
    <>
      <header className="sticky top-0 z-50 w-full bg-[#121212] py-4 shadow-md">
        <div className="container mx-auto flex items-center justify-between px-4 md:px-6">
          <Link
            className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x"
            href="#"
          >
            AI Central
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Services
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              About
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Industries
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Resources
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Contact
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Careers
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Tools
            </Link>
            <Link className="text-gray-400 hover:text-gray-200 transition-colors duration-300" href="#">
              Portfolio
            </Link>
          </nav>
          <Button className="hidden md:inline-flex" variant="gradient">
            Get Started
          </Button>
        </div>
      </header>
      <main>
        <section className="bg-[#121212] py-32">
          <div className="container mx-auto px-4 md:px-6">
            <h1 className="text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-6">
              Unlock the Power of AI
            </h1>
            <p className="text-gray-400 text-xl mb-10">
              AI Central provides cutting-edge AI consulting and research services to help businesses thrive in the
              digital age.
            </p>
            <div className="flex space-x-4">
              <Button className="px-6 py-3" variant="gradient">
                Explore Services
              </Button>
              <Button
                className="px-6 py-3 text-gray-400 hover:text-gray-200 transition-colors duration-300"
                variant="outline"
              >
                Learn More
              </Button>
            </div>
          </div>
        </section>
        <section className="bg-[#1e1e1e] py-32" id="services">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-10">
              Our Services
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-4">
                    AI Consulting
                  </h3>
                  <p className="text-gray-400">
                    Our team of AI experts will work with you to develop and implement custom AI solutions tailored to
                    your business needs.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-4">
                    AI Research
                  </h3>
                  <p className="text-gray-400">
                    Our cutting-edge research team explores the latest advancements in AI to help you stay ahead of the
                    curve.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-4">
                    AI Implementation
                  </h3>
                  <p className="text-gray-400">
                    We'll work with you to seamlessly integrate AI technologies into your existing systems and
                    workflows.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-[#121212] py-32" id="about">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-10">
              About AI Central
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <p className="text-gray-400 mb-6">
                  AI Central is a leading AI consulting and research firm dedicated to helping businesses harness the
                  power of artificial intelligence. Our team of experts work closely with clients to develop and
                  implement custom AI solutions that drive innovation and growth.
                </p>
                <p className="text-gray-400">
                  With a deep understanding of the latest AI technologies and industry trends, we are committed to
                  pushing the boundaries of what's possible and delivering transformative results for our clients.
                </p>
              </div>
              <div>
                <img
                  alt="AI Central Office"
                  className="rounded-lg object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#1e1e1e] py-32" id="industries">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-10">
              Industries We Serve
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-4">
                    Healthcare
                  </h3>
                  <p className="text-gray-400">
                    Leverage AI to improve patient outcomes, streamline operations, and drive innovation in the
                    healthcare industry.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Learn More
                    </Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-4">
                    Finance
                  </h3>
                  <p className="text-gray-400">
                    Optimize financial operations, improve risk management, and enhance customer experiences with
                    AI-powered solutions.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Learn More
                    </Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-4">
                    Retail
                  </h3>
                  <p className="text-gray-400">
                    Enhance customer experiences, optimize supply chains, and drive sales with AI-powered retail
                    solutions.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Learn More
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-[#121212] py-32" id="resources">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-10">
              Resources
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-4">
                    Blog
                  </h3>
                  <p className="text-gray-400">
                    Stay up-to-date with the latest AI trends, insights, and best practices from our industry experts.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Read More
                    </Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-4">
                    Whitepapers
                  </h3>
                  <p className="text-gray-400">
                    Dive deep into the latest AI research and industry analysis with our comprehensive whitepapers.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Download
                    </Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-4">
                    Webinars
                  </h3>
                  <p className="text-gray-400">
                    Join our experts for live webinars and interactive discussions on the latest AI trends and best
                    practices.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Register
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-[#1e1e1e] py-32" id="contact">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-10">
              Get in Touch
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <form className="space-y-6">
                  <div>
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter your name" required type="text" />
                  </div>
                  <div>
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="Enter your email" required type="email" />
                  </div>
                  <div>
                    <Label htmlFor="message">Message</Label>
                    <Textarea id="message" placeholder="Enter your message" required />
                  </div>
                  <Button className="w-full" type="submit" variant="gradient">
                    Send Message
                  </Button>
                </form>
              </div>
              <div>
                <div className="space-y-4">
                  <div className="flex items-center space-x-4">
                    <PhoneIcon className="text-gray-400 w-6 h-6" />
                    <p className="text-gray-400">+1 (123) 456-7890</p>
                  </div>
                  <div className="flex items-center space-x-4">
                    <MailOpenIcon className="text-gray-400 w-6 h-6" />
                    <p className="text-gray-400">info@aicentral.com</p>
                  </div>
                  <div className="flex items-center space-x-4">
                    <MapPinIcon className="text-gray-400 w-6 h-6" />
                    <p className="text-gray-400">123 Main St, Anytown USA</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#121212] py-32" id="careers">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#86a8e7] to-[#91eae4] animate-gradient-x mb-10">
              Join Our Team
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardContent className="text-center">
                  <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] animate-gradient-x mb-2">
                    AI Consultant
                  </h3>
                  <p className="text-gray-400">
                    Help our clients unlock the power of AI to drive innovation and growth.
                  </p>
                  <div className="mt-4">
                    <Button className="px-4 py-2 text-sm" variant="gradient">
                      Apply Now
                    </Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="text-center" />
              </Card>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

function MailOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.2 8.4c.5.38.8.97.8 1.6v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 .8-1.6l8-6a2 2 0 0 1 2.4 0l8 6Z" />
      <path d="m22 10-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 10" />
    </svg>
  )
}


function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
